name: Run Python Discord Bot

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Change this to the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bot/requirements.txt  # Change this to the path of your requirements file

    - name: Run the Discord bot
      run: |
        bot/main.py  # Adjust the path and filename accordingly
        sleep 180  # Wait for 3 minutes and then terminate
